In [1]:
from gurobipy import *
import numpy as np
import pandas as pd


#########Parameters Set-up############
# Read the data from the csv file and use the first column as the index of rows

project = pd.read_csv('OR Project Data.csv')
N,M = project.shape
print(project.columns)

Index(['Category', 'Food Name', 'Energy (kcal)', 'Protein (g)',
       'Total fat (g)', 'Saturated fat (g)', 'Dietary fibre (g)',
       'Carbohydrate (g)', 'Cholesterol (mg)', 'Sodium (mg)'],
      dtype='object')

In [2]:
project.head()

,Category,Food Name,Energy (kcal),Protein (g),Total fat (g),Saturated fat (g),Dietary fibre (g),Carbohydrate (g),Cholesterol (mg),Sodium (mg)
0,Main,Bak kut teh,323.71,28.11,23.43,9.37,0.00,0.00,153.34,1316.15
1,Main,Wanton noodles soup,318.04,25.14,7.00,1.85,1.74,36.57,76.03,1969.63
2,Main,Black carrot cake,556.47,13.16,26.74,10.05,1.54,65.77,205.80,1937.08
3,Main,Laksa (with rice vermicelli),695.50,27.30,39.65,14.24,3.90,57.85,104.00,7904.00
4,Main,Oyster omelette,668.10,18.60,51.09,20.70,0.00,33.54,366.80,772.90

In [3]:
nutrient = project.iloc[0:N, 2:M] 
nutrient.head()

,Energy (kcal),Protein (g),Total fat (g),Saturated fat (g),Dietary fibre (g),Carbohydrate (g),Cholesterol (mg),Sodium (mg)
0,323.71,28.11,23.43,9.37,0.00,0.00,153.34,1316.15
1,318.04,25.14,7.00,1.85,1.74,36.57,76.03,1969.63
2,556.47,13.16,26.74,10.05,1.54,65.77,205.80,1937.08
3,695.50,27.30,39.65,14.24,3.90,57.85,104.00,7904.00
4,668.10,18.60,51.09,20.70,0.00,33.54,366.80,772.90

In [4]:
energy = nutrient.iloc[0:N, 0]

In [5]:
constraints = pd.read_excel('OR Project Data Constraints.xlsx', index_col = 0, header= 0)
n,m = constraints.shape

#read in female 
req = constraints.iloc[:,2]

In [6]:
req

Nutrient
Energy (Kcal)        1800
Protein (g)            46
Total fat              69
Saturated fat          23
Fiber (g)              28
Carbohydrate (g)      130
Cholesterol           300
Sodium               2400
Name: 18-30 yrs Women, dtype: int64

In [7]:
req[0]

1800

In [13]:
m = Model("food")
n_dv = N

# Creat variables
x = m.addVars(N, vtype=GRB.BINARY, name = 'x')

# Set objective
m.setObjective( quicksum(x[i]*energy[i] for i in range(121)), GRB.MINIMIZE)
    
# Add constraints: 
m.addConstr( quicksum(x[i] for i in project[project.Category == 'Main'].index) ==2, name = "mains")
m.addConstr( quicksum(x[i] for i in project[project.Category == 'Breakfast'].index) ==1, name = "breakfast")
m.addConstr( quicksum(x[i] for i in  project[project.Category == 'Fruit'].index) <=2, name = "fruits")
m.addConstr( quicksum(x[i] for i in  project[project.Category == 'Dessert'].index) <=1, name = "dessert")
m.addConstr( quicksum(x[i] for i in  project[project.Category == 'Beverage'].index) <=2, name = "bev")

m.addConstrs( (quicksum(x[i]*nutrient.iloc[i, j] for i in range(121)) >= req[j] for j in [0,1,4,5])
             , name = "min_req")
m.addConstrs( (quicksum(x[i]*nutrient.iloc[i, j] for i in range(121)) <= req[j] for j in [2,3,6,7])
             , name = "max_intake")

{2: <gurobi.Constr *Awaiting Model Update*>,
 3: <gurobi.Constr *Awaiting Model Update*>,
 6: <gurobi.Constr *Awaiting Model Update*>,
 7: <gurobi.Constr *Awaiting Model Update*>}

In [14]:
project.iloc[1,2]

318.04

In [15]:
# Solving the model
m.setParam( 'OutputFlag', False )
m.optimize()

#  Print optimal solutions and optimal value
for v in m.getVars():
    if(v.x == 1):
        print(v.VarName, v.x)
    
print('Obj:', m.objVal)

x[48] 1.0
x[49] 1.0
x[65] 1.0
x[70] 1.0
x[82] 1.0
x[84] 1.0
x[90] 1.0
x[100] 1.0
Obj: 1800.1099999999997

In [16]:
project.iloc[[48,49,65,70,82,84,90,100]]

,Category,Food Name,Energy (kcal),Protein (g),Total fat (g),Saturated fat (g),Dietary fibre (g),Carbohydrate (g),Cholesterol (mg),Sodium (mg)
48,Main,"French fries, medium, McDonald's",373.52,3.48,19.00,7.60,4.00,47.00,0.0,290.00
49,Main,Beef and Teriyaki Chicken Bento,743.28,43.03,20.88,7.92,10.76,95.35,0.0,1515.90
65,Dessert,"Soya bean curd, less sweet",263.13,12.35,3.22,0.59,1.61,45.65,0.0,32.22
70,Beverage,"Soya bean milk, without sugar",82.50,6.75,5.00,0.65,2.00,3.00,0.0,30.00
82,Beverage,"Coconut flesh, young",64.60,1.87,2.55,2.23,0.85,8.50,0.0,15.30
84,Fruit,Dragonfruit,105.84,2.81,0.22,0.04,5.83,22.90,0.0,25.92
90,Fruit,Banana,93.00,1.08,0.15,0.05,2.00,21.91,0.0,16.91
100,Breakfast,"Red rice porridge, plain",74.24,2.30,0.51,0.15,1.02,15.10,0.0,7.68